services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: stego_frontend
    volumes:
      - steg-analyze-data:/app/static/uploads
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stego_backend
    volumes:
      - steg-analyze-data:/app/uploads
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: xander
      MONGO_INITDB_ROOT_PASSWORD: xander21
      MONGO_INITDB_DATABASE: flaskdb
    volumes:
      - stego-db:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./static/uploads:/uploads

    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  steg-analyze-data:
  stego-db:
